### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid control character at: line 5 column 55 (char 179)

### ISSUE THREAD

**Issue by TanjimReza** [ksssomesh12/tgmb-beta#20] opened 2021-10-21 17:38 UTC
Heroku suspends the app right after pushing 
`Setting stack to container... done
You will need to redeploy ⬢ gglolapp for the change to take effect.
Run git push heroku main to trigger a new build on ⬢ gglolapp.
$ git push heroku master
remote: !       The application "gglolapp" was suspended. If you believe this is an error please contact support.
fatal: unable to access 'https://git.heroku.com/gglolapp.git/': The requested URL returned error: 403`

What is this issue? 
`Generated 'config.template.json' !
Do You Want to Use Dynamic Config? n
Do You Want to Update Config? y
Do You Want to Use User Account Auth? n
Traceback (most recent call last):
  File "setup.py", line 171, in <module>
    configVars = {**configTemplateVars, **jsonFileLoad(configJsonFile)}
  File "setup.py", line 60, in jsonFileLoad
    return json.loads(open(jsonFileName, 'rt', encoding='utf-8').read())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 5 column 55 (char 179)`

**Comment by ksssomesh12** [comment] 2021-10-23 04:23
[config.txt](https://github.com/ksssomesh12/tgmb-beta/files/7402256/config.txt)

**Comment by TanjimReza** [comment] 2021-10-23 19:03
Is your deployment running on heroku?

**Comment by ksssomesh12** [comment] 2021-10-25 04:56
It works perfectly fine for me. Actually, it has been for 3 months or so, without any hiccups at all.
BTW, did u deploy correctly? Are u running setup.py in container? If yes, that's a mis-step.

**Comment by TanjimReza** [comment] 2021-10-25 14:43
Running setup.py in deploy folder then pushing the main directory to heroku. There's no instruction on README regarding this. If possible then correct me.

**Comment by TanjimReza** [comment] 2021-10-25 15:41
Even after deploying, It gets suspended in 1mins. Can you try a new deploy?

Deploying from deploy folder

```
2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
2021-10-25T16:15:58.846790+00:00 app[worker.1]:     return _default_decoder.decode(s)
2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
2021-10-25T16:15:58.846790+00:00 app[worker.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
2021-10-25T16:15:58.846791+00:00 app[worker.1]:     obj, end = self.scan_once(s, idx)
2021-10-25T16:15:58.846792+00:00 app[worker.1]: json.decoder.JSONDecodeError: Invalid control character at: line 5 column 55 (char 179)
```

**Comment by ksssomesh12** [comment] 2021-10-27 09:02
You are doing it wrong. Deploy using the dockerfile in deploy folder. Deploy folder should be the root of the git repository u r pushing to heroku.

**Comment by TanjimReza** [comment] 2021-10-27 09:04
Doing the same, here's the dockerfile contents that I am pushing, that's on deploy folder 
```
FROM ghcr.io/ksssomesh12/tgmb-beta:master
COPY . .
```

**Comment by ksssomesh12** [comment] 2021-10-27 09:07
Then you wont be building the telegram bot api binaries. Have u tried deploying locally and test with that?

**Comment by TanjimReza** [comment] 2021-10-27 09:59
I have tried, just after deploying it gets banned no matter what. I don't know how yours one is still running.

**Comment by ksssomesh12** [comment] 2021-10-27 12:30
> Even after deploying, It gets suspended in 1mins. Can you try a new deploy?
> 
> Deploying from deploy folder
> 
> ```
> 2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
> 2021-10-25T16:15:58.846790+00:00 app[worker.1]:     return _default_decoder.decode(s)
> 2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
> 2021-10-25T16:15:58.846790+00:00 app[worker.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> 2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
> 2021-10-25T16:15:58.846791+00:00 app[worker.1]:     obj, end = self.scan_once(s, idx)
> 2021-10-25T16:15:58.846792+00:00 app[worker.1]: json.decoder.JSONDecodeError: Invalid control character at: line 5 column 55 (char 179)
> ```

What is the character at line 5 column 55? Also, I think you can understand that I as a matter of fact has to edit-deploy-test-repeat at a very high frequenct as part of my workflow. So far, I haven't faced the exception you are encountering here.

**Comment by TanjimReza** [comment] 2021-10-27 12:58
> > Even after deploying, It gets suspended in 1mins. Can you try a new deploy?
> > 
> > Deploying from deploy folder
> > 
> > ```
> > 2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
> > 2021-10-25T16:15:58.846790+00:00 app[worker.1]:     return _default_decoder.decode(s)
> > 2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
> > 2021-10-25T16:15:58.846790+00:00 app[worker.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > 2021-10-25T16:15:58.846790+00:00 app[worker.1]:   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
> > 2021-10-25T16:15:58.846791+00:00 app[worker.1]:     obj, end = self.scan_once(s, idx)
> > 2021-10-25T16:15:58.846792+00:00 app[worker.1]: json.decoder.JSONDecodeError: Invalid control character at: line 5 column 55 (char 179)
> > ```
> 
> What is the character at line 5 column 55? Also, I think you can understand that I as a matter of fact has to edit-deploy-test-repeat at a very high frequenct as part of my workflow. So far, I haven't faced the exception you are encountering here.

That problem has been solved, I got the created config message. Yet, after deploying it gets banned. I can send you some screenshots. (Deploy folder is the root folder)

**Comment by ksssomesh12** [comment] 2021-10-27 15:27
Reach me on [Telegram](https://t.me/ksssomesh12).

**Comment by ksssomesh12** [comment] 2021-11-02 08:23
Closing this temporarily. Feel free to reopen if still the issue is not resolved.

**Closed as completed by ksssomesh12** 2021-11-02 08:23 UTC
